movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views


movie_resource = MovieResource()

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls)),
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie


class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['date_created', 'number_in_stock']

movies/models.py
from django.db import models
from django.utils import timezone


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete='models.CASCADE')
    date_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie


def index(request):
    movies = Movie.objects.all()
    # output = ', '.join([m.title for m in movies])
    return render(request, 'movies/index.html', {'movies': movies})


def detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

vidly/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block content %}
    <dl>
        <dt>Title</dt>
        <dd>{{ movie.title }}</dd>
        <dt>Genre</dt>
        <dd>{{ movie.genre }}</dd>
        <dt>Stock</dt>
        <dd>{{ movie.number_in_stock }}</dd>
    </dl>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}


{% block content %}
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Genre</th>
                    <th>Stock</th>
                    <th>Daily Rate</th>
                </tr>
            </thead>
            <tbody>
                {% for movie in movies %}
                <tr>
                    <td>
                        <a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a>
                    </td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.number_in_stock }}</td>
                    <td>{{ movie.daily_rate }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Vidly: The Video Rental Shop</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-dark primary-color">
      <a class="navbar-brand font-weight-bold" href="#">
        <!-- <img src="https://mdbootstrap.com/img/logo/mdb-transparent.png" height="30" class="d-inline-block align-top"
          alt="mdb logo"> --> <i class="fas fa-video"></i> VIDLY
      </a>
    </nav>

    <div class="clearfix py-3"></div>

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
  <!-- SCRIPTS -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/popper.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/js/mdb.min.js"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'movies:index' %}">Movies</a>
{% endblock %}